spring:
  dubbo:
    application:
      name: provider # \u670D\u52A1\u540D\u79F0
    registry:
      address: zookeeper://127.0.0.1:2181 # \u6CE8\u518C\u4E2D\u5FC3\u3001
    protocol:
      name: dubbo
      port: 20880
    scan: com.minnie.provider.service
